export interface BrazilState {
  code: string
  name: string
  capital: string
}

export const BRAZIL_STATES: BrazilState[] = [
  { code: 'AC', name: 'Acre', capital: 'Rio Branco' },
  { code: 'AL', name: 'Alagoas', capital: 'Maceio' },
  { code: 'AP', name: 'Amapa', capital: 'Macapa' },
  { code: 'AM', name: 'Amazonas', capital: 'Manaus' },
  { code: 'BA', name: 'Bahia', capital: 'Salvador' },
  { code: 'CE', name: 'Ceara', capital: 'Fortaleza' },
  { code: 'DF', name: 'Distrito Federal', capital: 'Brasilia' },
  { code: 'ES', name: 'Espirito Santo', capital: 'Vitoria' },
  { code: 'GO', name: 'Goias', capital: 'Goiania' },
  { code: 'MA', name: 'Maranhao', capital: 'Sao Luis' },
  { code: 'MT', name: 'Mato Grosso', capital: 'Cuiaba' },
  { code: 'MS', name: 'Mato Grosso do Sul', capital: 'Campo Grande' },
  { code: 'MG', name: 'Minas Gerais', capital: 'Belo Horizonte' },
  { code: 'PA', name: 'Para', capital: 'Belem' },
  { code: 'PB', name: 'Paraiba', capital: 'Joao Pessoa' },
  { code: 'PR', name: 'Parana', capital: 'Curitiba' },
  { code: 'PE', name: 'Pernambuco', capital: 'Recife' },
  { code: 'PI', name: 'Piaui', capital: 'Teresina' },
  { code: 'RJ', name: 'Rio de Janeiro', capital: 'Rio de Janeiro' },
  { code: 'RN', name: 'Rio Grande do Norte', capital: 'Natal' },
  { code: 'RS', name: 'Rio Grande do Sul', capital: 'Porto Alegre' },
  { code: 'RO', name: 'Rondonia', capital: 'Porto Velho' },
  { code: 'RR', name: 'Roraima', capital: 'Boa Vista' },
  { code: 'SC', name: 'Santa Catarina', capital: 'Florianopolis' },
  { code: 'SP', name: 'Sao Paulo', capital: 'Sao Paulo' },
  { code: 'SE', name: 'Sergipe', capital: 'Aracaju' },
  { code: 'TO', name: 'Tocantins', capital: 'Palmas' },
]

export const BRAZIL_DDDS = [
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '21',
  '22',
  '24',
  '27',
  '28',
  '31',
  '32',
  '33',
  '34',
  '35',
  '37',
  '38',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '51',
  '53',
  '54',
  '55',
  '61',
  '62',
  '63',
  '64',
  '65',
  '66',
  '67',
  '68',
  '69',
  '71',
  '73',
  '74',
  '75',
  '77',
  '79',
  '81',
  '82',
  '83',
  '84',
  '85',
  '86',
  '87',
  '88',
  '89',
  '91',
  '92',
  '93',
  '94',
  '95',
  '96',
  '97',
  '98',
  '99',
] as const

export const BRAZIL_FIRST_NAMES = [
  'Ana',
  'Beatriz',
  'Bruno',
  'Caio',
  'Camila',
  'Carla',
  'Catarina',
  'Daniel',
  'Diego',
  'Eduarda',
  'Elaine',
  'Felipe',
  'Fernanda',
  'Gabriel',
  'Gabriela',
  'Gustavo',
  'Helena',
  'Hugo',
  'Isabela',
  'Joana',
  'Joao',
  'Julia',
  'Karina',
  'Larissa',
  'Leticia',
  'Lucas',
  'Luiza',
  'Marcelo',
  'Mariana',
  'Matheus',
  'Nicolas',
  'Olivia',
  'Paulo',
  'Pedro',
  'Rafael',
  'Renata',
  'Ricardo',
  'Sabrina',
  'Samuel',
  'Thiago',
  'Vanessa',
  'Vitor',
] as const

export const BRAZIL_LAST_NAMES = [
  'Almeida',
  'Alves',
  'Araujo',
  'Barbosa',
  'Batista',
  'Campos',
  'Cardoso',
  'Carvalho',
  'Castro',
  'Costa',
  'Dias',
  'Duarte',
  'Fernandes',
  'Ferreira',
  'Gomes',
  'Lima',
  'Machado',
  'Marques',
  'Martins',
  'Mendes',
  'Melo',
  'Moraes',
  'Moreira',
  'Nascimento',
  'Oliveira',
  'Pereira',
  'Ribeiro',
  'Rocha',
  'Rodrigues',
  'Santana',
  'Santos',
  'Silva',
  'Soares',
  'Souza',
  'Teixeira',
  'Vieira',
] as const
