import { describe, expect, it } from 'vitest'

import { BRAZIL_DDDS, BRAZIL_STATES } from './brazil'

describe('brazil datasets', () => {
  it('contains all 27 brazilian states', () => {
    const codes = BRAZIL_STATES.map((state) => state.code)

    expect(codes).toHaveLength(27)
    expect(new Set(codes).size).toBe(27)
    expect(codes).toEqual(
      expect.arrayContaining([
        'AC',
        'AL',
        'AP',
        'AM',
        'BA',
        'CE',
        'DF',
        'ES',
        'GO',
        'MA',
        'MT',
        'MS',
        'MG',
        'PA',
        'PB',
        'PR',
        'PE',
        'PI',
        'RJ',
        'RN',
        'RS',
        'RO',
        'RR',
        'SC',
        'SP',
        'SE',
        'TO',
      ]),
    )
  })

  it('contains all valid brazilian DDD codes', () => {
    expect(BRAZIL_DDDS).toEqual(
      expect.arrayContaining([
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '21',
        '22',
        '24',
        '27',
        '28',
        '31',
        '32',
        '33',
        '34',
        '35',
        '37',
        '38',
        '41',
        '42',
        '43',
        '44',
        '45',
        '46',
        '47',
        '48',
        '49',
        '51',
        '53',
        '54',
        '55',
        '61',
        '62',
        '63',
        '64',
        '65',
        '66',
        '67',
        '68',
        '69',
        '71',
        '73',
        '74',
        '75',
        '77',
        '79',
        '81',
        '82',
        '83',
        '84',
        '85',
        '86',
        '87',
        '88',
        '89',
        '91',
        '92',
        '93',
        '94',
        '95',
        '96',
        '97',
        '98',
        '99',
      ]),
    )
    expect(new Set(BRAZIL_DDDS).size).toBe(BRAZIL_DDDS.length)
  })
})
